# SPDX-License-Identifier: PMPL-1.0-or-later
# StreamData property tests for PolyglotFormalisms mathematical invariants.
#
# Each formalism module claims specific algebraic properties (commutativity,
# associativity, identity elements, De Morgan's laws, etc.). These property
# tests verify those claims hold for arbitrary inputs generated by StreamData.

defmodule PolyglotFormalisms.PropertyTest do
  use ExUnit.Case, async: true
  use ExUnitProperties

  alias PolyglotFormalisms.Arithmetic
  alias PolyglotFormalisms.Comparison
  alias PolyglotFormalisms.Logical
  alias PolyglotFormalisms.StringOps

  # ---------------------------------------------------------------------------
  # Arithmetic properties
  # ---------------------------------------------------------------------------

  describe "Arithmetic: addition algebraic laws" do
    property "commutativity: add(a, b) == add(b, a)" do
      check all a <- StreamData.integer(), b <- StreamData.integer() do
        assert Arithmetic.add(a, b) == Arithmetic.add(b, a)
      end
    end

    property "associativity: add(add(a, b), c) == add(a, add(b, c))" do
      check all a <- StreamData.integer(),
                b <- StreamData.integer(),
                c <- StreamData.integer() do
        assert Arithmetic.add(Arithmetic.add(a, b), c) ==
               Arithmetic.add(a, Arithmetic.add(b, c))
      end
    end

    property "identity element: add(a, 0) == a" do
      check all a <- StreamData.integer() do
        assert Arithmetic.add(a, 0) == a
      end
    end
  end

  describe "Arithmetic: multiplication algebraic laws" do
    property "commutativity: multiply(a, b) == multiply(b, a)" do
      check all a <- StreamData.integer(), b <- StreamData.integer() do
        assert Arithmetic.multiply(a, b) == Arithmetic.multiply(b, a)
      end
    end

    property "associativity: multiply(multiply(a, b), c) == multiply(a, multiply(b, c))" do
      check all a <- StreamData.integer(),
                b <- StreamData.integer(),
                c <- StreamData.integer() do
        assert Arithmetic.multiply(Arithmetic.multiply(a, b), c) ==
               Arithmetic.multiply(a, Arithmetic.multiply(b, c))
      end
    end

    property "identity element: multiply(a, 1) == a" do
      check all a <- StreamData.integer() do
        assert Arithmetic.multiply(a, 1) == a
      end
    end

    property "zero annihilator: multiply(a, 0) == 0" do
      check all a <- StreamData.integer() do
        assert Arithmetic.multiply(a, 0) == 0
      end
    end
  end

  describe "Arithmetic: subtraction" do
    property "identity: subtract(a, 0) == a" do
      check all a <- StreamData.integer() do
        assert Arithmetic.subtract(a, 0) == a
      end
    end

    property "anti-commutativity: subtract(a, b) == negate(subtract(b, a))" do
      check all a <- StreamData.integer(), b <- StreamData.integer() do
        assert Arithmetic.subtract(a, b) == -Arithmetic.subtract(b, a)
      end
    end
  end

  describe "Arithmetic: division" do
    property "identity: divide(a, 1) == a as float" do
      check all a <- StreamData.integer() do
        assert Arithmetic.divide(a, 1) == a * 1.0
      end
    end

    property "divide(a, a) == 1.0 for non-zero a" do
      check all a <- StreamData.filter(StreamData.integer(), &(&1 != 0)) do
        assert_in_delta Arithmetic.divide(a, a), 1.0, 1.0e-9
      end
    end
  end

  # ---------------------------------------------------------------------------
  # Comparison properties
  # ---------------------------------------------------------------------------

  describe "Comparison: total order laws" do
    property "reflexivity: equal(a, a)" do
      check all a <- StreamData.integer() do
        assert Comparison.equal(a, a)
      end
    end

    property "symmetry: equal(a, b) iff equal(b, a)" do
      check all a <- StreamData.integer(), b <- StreamData.integer() do
        assert Comparison.equal(a, b) == Comparison.equal(b, a)
      end
    end

    property "transitivity of less_than: a < b && b < c => a < c" do
      check all a <- StreamData.integer(),
                diff1 <- StreamData.positive_integer(),
                diff2 <- StreamData.positive_integer() do
        b = a + diff1
        c = b + diff2

        assert Comparison.less_than(a, b)
        assert Comparison.less_than(b, c)
        assert Comparison.less_than(a, c)
      end
    end

    property "irreflexivity: not less_than(a, a)" do
      check all a <- StreamData.integer() do
        refute Comparison.less_than(a, a)
      end
    end

    property "asymmetry: less_than(a, b) => not less_than(b, a)" do
      check all a <- StreamData.integer(), diff <- StreamData.positive_integer() do
        b = a + diff
        assert Comparison.less_than(a, b)
        refute Comparison.less_than(b, a)
      end
    end

    property "trichotomy: exactly one of less_than(a,b), equal(a,b), greater_than(a,b)" do
      check all a <- StreamData.integer(), b <- StreamData.integer() do
        lt = Comparison.less_than(a, b)
        eq = Comparison.equal(a, b)
        gt = Comparison.greater_than(a, b)

        true_count = [lt, eq, gt] |> Enum.count(& &1)
        assert true_count == 1
      end
    end
  end

  # ---------------------------------------------------------------------------
  # Logical properties
  # ---------------------------------------------------------------------------

  describe "Logical: boolean algebra laws" do
    property "De Morgan (AND): not(a and b) == (not a) or (not b)" do
      check all a <- StreamData.boolean(), b <- StreamData.boolean() do
        lhs = Logical.logical_not(Logical.logical_and(a, b))
        rhs = Logical.logical_or(Logical.logical_not(a), Logical.logical_not(b))
        assert lhs == rhs
      end
    end

    property "De Morgan (OR): not(a or b) == (not a) and (not b)" do
      check all a <- StreamData.boolean(), b <- StreamData.boolean() do
        lhs = Logical.logical_not(Logical.logical_or(a, b))
        rhs = Logical.logical_and(Logical.logical_not(a), Logical.logical_not(b))
        assert lhs == rhs
      end
    end

    property "double negation: not(not(a)) == a" do
      check all a <- StreamData.boolean() do
        assert Logical.logical_not(Logical.logical_not(a)) == a
      end
    end

    property "AND commutativity: and(a, b) == and(b, a)" do
      check all a <- StreamData.boolean(), b <- StreamData.boolean() do
        assert Logical.logical_and(a, b) == Logical.logical_and(b, a)
      end
    end

    property "OR commutativity: or(a, b) == or(b, a)" do
      check all a <- StreamData.boolean(), b <- StreamData.boolean() do
        assert Logical.logical_or(a, b) == Logical.logical_or(b, a)
      end
    end

    property "AND identity: and(a, true) == a" do
      check all a <- StreamData.boolean() do
        assert Logical.logical_and(a, true) == a
      end
    end

    property "OR identity: or(a, false) == a" do
      check all a <- StreamData.boolean() do
        assert Logical.logical_or(a, false) == a
      end
    end

    property "AND annihilator: and(a, false) == false" do
      check all a <- StreamData.boolean() do
        assert Logical.logical_and(a, false) == false
      end
    end

    property "OR annihilator: or(a, true) == true" do
      check all a <- StreamData.boolean() do
        assert Logical.logical_or(a, true) == true
      end
    end
  end

  # ---------------------------------------------------------------------------
  # StringOps properties
  # ---------------------------------------------------------------------------

  describe "StringOps: string algebra laws" do
    property "concat identity: concat(s, \"\") == s" do
      check all s <- StreamData.string(:printable) do
        assert StringOps.concat(s, "") == s
      end
    end

    property "concat associativity: concat(concat(a, b), c) == concat(a, concat(b, c))" do
      check all a <- StreamData.string(:printable, max_length: 50),
                b <- StreamData.string(:printable, max_length: 50),
                c <- StreamData.string(:printable, max_length: 50) do
        assert StringOps.concat(StringOps.concat(a, b), c) ==
               StringOps.concat(a, StringOps.concat(b, c))
      end
    end

    property "string_length is non-negative" do
      check all s <- StreamData.string(:printable) do
        assert StringOps.string_length(s) >= 0
      end
    end

    property "string_length(concat(a, b)) == string_length(a) + string_length(b)" do
      check all a <- StreamData.string(:alphanumeric, max_length: 100),
                b <- StreamData.string(:alphanumeric, max_length: 100) do
        joined = StringOps.concat(a, b)
        assert StringOps.string_length(joined) ==
               StringOps.string_length(a) + StringOps.string_length(b)
      end
    end
  end
end
